on: 
  workflow_dispatch:
    inputs:
      ncurses_version:
        description: 'The version of Ncurses to bake in'
        default: "6.3"
        required: true
      openssl_version:
        description: 'The version of OpenSSL to bake in'
        default: "1.1.1n"
        required: true
      erlang_version:
        description: 'The Erlang version to build'
        required: true

jobs:
  ensure_release:
    runs-on: ubuntu-18.04
    name: "Ensure release (${{ github.event.inputs.erlang_version }})"
    steps:
      - run: gh api -XHEAD repos/erlang/otp/releases/tags/OTP-${{ github.event.inputs.erlang_version }}
        name: Check erlang/otp
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - id: check-release
        name: Check burrito-elixir/beam-machine-darwin 
        run: |
          if gh api -XHEAD repos/burrito-elixir/beam-machine-darwin/releases/tags/OTP-${{ github.event.inputs.erlang_version }}; then 
            echo ::set-output name=exists::$(echo true)
          else
            echo ::set-output name=exists::$(echo false)
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          owner: burrito-elixir
          repo: beam-machine-darwin
          commitish: main
          tag_name: OTP-${{ github.event.inputs.erlang_version }}
          prerelease: ${{ contains(github.event.inputs.erlang_version, 'rc') }}
        if: ${{ steps.check-release.outputs.exists == 'false' }}

  build-macos-aarch64:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Erlang (aarch64)
      run: brew install elixir && elixir ./mkerlang.exs --arch=aarch64 --otp-version="${{ github.event.inputs.erlang_version }}" --openssl-version="${{ github.event.inputs.openssl_version }}" --ncurses-version="${{ github.event.inputs.ncurses_version }}"
    - run: gh release upload -R burrito-elixir/beam-machine-darwin OTP-${{ github.event.inputs.erlang_version }} ./*.tar.gz
      name: Upload Base Archive
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-macos-x86_64:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Erlang (x86_64)
      run: brew install elixir && elixir ./mkerlang.exs --arch=x86_64 --otp-version="${{ github.event.inputs.erlang_version }}" --openssl-version="${{ github.event.inputs.openssl_version }}" --ncurses-version="${{ github.event.inputs.ncurses_version }}"
    - run: gh release upload -R burrito-elixir/beam-machine-darwin OTP-${{ github.event.inputs.erlang_version }} ./*.tar.gz
      name: Upload Base Archive
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}